# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Clique' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

pod 'GooglePlaces', '7.2.0'
  

end
